// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvtu2-TZegWwvlBVf8BPIkqZ4e2S-eFNY',
    appId: '1:151247547799:web:f4b1b18ea0a66f4aea68d2',
    messagingSenderId: '151247547799',
    projectId: 'my-library-management-app',
    authDomain: 'my-library-management-app.firebaseapp.com',
    storageBucket: 'my-library-management-app.appspot.com',
    measurementId: 'G-20Z2DW20F9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2Y-ZR2K76mYGZThIX8s20wCXSdBUYuZU',
    appId: '1:151247547799:android:edb083aeb0c3fceeea68d2',
    messagingSenderId: '151247547799',
    projectId: 'my-library-management-app',
    storageBucket: 'my-library-management-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDczOX7pKIYa9uthTFsZTYd8jTDffAVNRk',
    appId: '1:151247547799:ios:af92226b83ba234bea68d2',
    messagingSenderId: '151247547799',
    projectId: 'my-library-management-app',
    storageBucket: 'my-library-management-app.appspot.com',
    iosBundleId: 'com.example.libraryManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDczOX7pKIYa9uthTFsZTYd8jTDffAVNRk',
    appId: '1:151247547799:ios:af92226b83ba234bea68d2',
    messagingSenderId: '151247547799',
    projectId: 'my-library-management-app',
    storageBucket: 'my-library-management-app.appspot.com',
    iosBundleId: 'com.example.libraryManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvtu2-TZegWwvlBVf8BPIkqZ4e2S-eFNY',
    appId: '1:151247547799:web:871f17597361b54bea68d2',
    messagingSenderId: '151247547799',
    projectId: 'my-library-management-app',
    authDomain: 'my-library-management-app.firebaseapp.com',
    storageBucket: 'my-library-management-app.appspot.com',
    measurementId: 'G-3V47J0BN4H',
  );

}